Repository autonomousapps/dependency-analysis-gradle-plugin, pull requests merged in 2020-11, with the labels that each got.

#316 Remove task execution listener.
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/internal/UnitTestCompilationFailureListener.kt
Labels: enhancement

#317 Optimized GraphBuilder. Don't visit same node more than once.
  src/main/kotlin/com/autonomousapps/tasks/DependencyGraphTask.kt
Labels: enhancement

#319 Add system property to configure enabling of test-related code analysis.
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/Flags.kt
  src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
  src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
Labels: enhancement

#320 Add tasks to view project dependency graphs.
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/graph/DependencyGraph.kt
  src/main/kotlin/com/autonomousapps/graph/DepthFirstSearch.kt
  src/main/kotlin/com/autonomousapps/internal/ConfigurationsToDependenciesTransformer.kt
  src/main/kotlin/com/autonomousapps/internal/OutputPaths.kt
  src/main/kotlin/com/autonomousapps/internal/advice/RippleWriter.kt
  src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
  src/main/kotlin/com/autonomousapps/internal/analyzer/DependencyAnalyzer.kt
  src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
  src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
  src/main/kotlin/com/autonomousapps/tasks/DependencyGraphAggregationTask.kt
  src/main/kotlin/com/autonomousapps/tasks/LocateDependenciesTask.kt
  src/main/kotlin/com/autonomousapps/tasks/ProjectGraphAggregationTask.kt
  src/main/kotlin/com/autonomousapps/tasks/ProjectGraphTask.kt
Labels: enhancement

#323 New system property to configure clearing of assemble artifacts. Use forUseAtConfigurationTime().
  settings.gradle.kts
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/Flags.kt
  src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
  src/main/kotlin/com/autonomousapps/internal/analyzer/JvmProjectAnalyzer.kt
Labels: bug, enhancement

#324 Annotations on or in public classes are part of the ABI. This includes:
  src/functionalTest/groovy/com/autonomousapps/android/AndroidKotlinInlineSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/android/CoreKtxSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/android/OtherAndroidSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/AdviceFilterProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidKotlinInlineProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/TestSourceProject.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/ConstantsProject.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/RedundantPluginsProject.groovy
  src/functionalTest/kotlin/com/autonomousapps/fixtures/AnotherCompileOnlyProject.kt
  src/functionalTest/kotlin/com/autonomousapps/fixtures/CompileOnlyTestProject.kt
  src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
  src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
  src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
  src/main/kotlin/com/autonomousapps/internal/models.kt
  src/main/kotlin/com/autonomousapps/tasks/BuildHealthTask.kt
Labels: bug

#325 Regresion tests for annotations/abi behavior.
  src/functionalTest/groovy/com/autonomousapps/jvm/AnnotationsAbiSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/AnnotationsAbiProject.groovy
  src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
Labels: testing

#326 Test for SOURCE-retention annotations. They can be compileOnly.
  src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/AnnotationsAbiSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/AnnotationsAbiProject.groovy
Labels: testing

#329 Generic types can be part of the ABI.
  src/functionalTest/groovy/com/autonomousapps/jvm/AbiAnnotationsSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/AbiGenericsSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiAnnotationsProject.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiGenericsProject.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/GenericsProject.groovy
  src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
  src/main/kotlin/com/autonomousapps/internal/kotlin/abiDependencies.kt
  src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
  src/main/kotlin/com/autonomousapps/internal/utils/regex.kt
Labels: bug

#330 Class references used by annotations are part of the ABI.
  src/functionalTest/groovy/com/autonomousapps/jvm/AbiAnnotationsSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/AbiAnnotationsProject.groovy
  src/main/kotlin/com/autonomousapps/internal/asm.kt
  src/main/kotlin/com/autonomousapps/internal/kotlin/PublicApiDump.kt
  src/main/kotlin/com/autonomousapps/internal/kotlin/asmUtils.kt
  src/main/kotlin/com/autonomousapps/internal/utils/regex.kt
Labels: bug

#338 Bump Gradle to 6.7.1 and update test matrix.
  gradle/wrapper/gradle-wrapper.properties
  src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/internal/AnalyzedJar.kt
Labels: maintenance

#336 Update supported version of AGP to 4.2.0-alpha16
  CHANGELOG.md
  src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
  src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
Labels: maintenance
