Repository autonomousapps/dependency-analysis-gradle-plugin, pull requests merged in 2020-06, with the labels that each got.

#186 Improved DSL.
  gradle.properties
  src/functionalTest/groovy/com/autonomousapps/AdviceHelper.groovy
  src/functionalTest/groovy/com/autonomousapps/android/AdviceSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/AdviceFilterProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/ServiceLoaderProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/VariantProject.groovy
  src/functionalTest/kotlin/com/autonomousapps/fixtures/adviceTestProject.kt
  src/functionalTest/kotlin/com/autonomousapps/utils/runner.kt
  src/main/kotlin/com/autonomousapps/AbstractExtension.kt
  src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/DependencyAnalysisSubExtension.kt
  src/main/kotlin/com/autonomousapps/advice/BuildHealth.kt
  src/main/kotlin/com/autonomousapps/extension/AbiHandler.kt
  src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
  src/main/kotlin/com/autonomousapps/internal/advice/filter/FilterSpec.kt
  src/main/kotlin/com/autonomousapps/tasks/AdviceAggregateReportTask.kt
  src/main/kotlin/com/autonomousapps/tasks/AdviceSubprojectAggregationTask.kt
  src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
  src/main/kotlin/com/autonomousapps/tasks/FailOrWarnTask.kt
  src/test/kotlin/com/autonomousapps/internal/ConsoleReportTest.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/AndroidBlock.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/AndroidManifest.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/AndroidSubproject.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/Plugin.kt
Labels: enhancement

#191 Building upon and formalizing the concept of 'facade groups'.
  CHANGELOG.md
  src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/DependenciesSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/FacadeFilterSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/AdviceFilterProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidThreeTenProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/KotlinStdlibProject.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/AbstractJvmSpec.groovy
  src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/advice/ComponentWithTransitives.kt
  src/main/kotlin/com/autonomousapps/advice/TransitiveDependency.kt
  src/main/kotlin/com/autonomousapps/extension/DependenciesHandler.kt
  src/main/kotlin/com/autonomousapps/extension/IssueHandler.kt
  src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt
  src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt
  src/main/kotlin/com/autonomousapps/internal/advice/filter/DependencyBundleFilter.kt
  src/main/kotlin/com/autonomousapps/internal/advice/filter/FacadeFilter.kt
  src/main/kotlin/com/autonomousapps/internal/advice/filter/FilterSpec.kt
  src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
  src/test/groovy/com/autonomousapps/internal/advice/filter/FacadeFilterTest.groovy
  src/test/kotlin/com/autonomousapps/advice/ComponentWithTransitivesTest.kt
  src/test/kotlin/com/autonomousapps/extension/BundleHandlerTest.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/AndroidManifest.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
Labels: enhancement

#192 Fixed bug in RedundantKaptAlertTask and use workers.
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/RedundantPluginSubPlugin.kt
  src/main/kotlin/com/autonomousapps/tasks/RedundantKaptAlertTask.kt
Labels: bug, enhancement

#193 Build and test against Gradle 6.5.
  CHANGELOG.md
  gradle/wrapper/gradle-wrapper.properties
  src/functionalTest/groovy/com/autonomousapps/AbstractFunctionalSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/android/AbstractAndroidSpec.groovy
  src/main/kotlin/com/autonomousapps/internal/android/AgpVersion.kt
Labels: maintenance

#195 Simplify logging.
  CHANGELOG.md
  src/main/kotlin/com/autonomousapps/DependencyAnalysisExtension.kt
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/RedundantPluginSubPlugin.kt
  src/main/kotlin/com/autonomousapps/advice/PluginAdvice.kt
  src/main/kotlin/com/autonomousapps/internal/utils/utils.kt
  src/main/kotlin/com/autonomousapps/tasks/AdviceAggregateReportTask.kt
  src/main/kotlin/com/autonomousapps/tasks/AdvicePrinterTask.kt
  src/main/kotlin/com/autonomousapps/tasks/AdviceSubprojectAggregationTask.kt
  src/main/kotlin/com/autonomousapps/tasks/AdviceTask.kt
  src/main/kotlin/com/autonomousapps/tasks/FailOrWarnTask.kt
  src/main/kotlin/com/autonomousapps/tasks/RedundantKaptAlertTask.kt
  src/main/kotlin/com/autonomousapps/tasks/RedundantPluginAlertTask.kt
Labels: enhancement

#196 Improving testkit.
  src/functionalTest/groovy/com/autonomousapps/android/projects/AdviceFilterProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/AndroidThreeTenProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/KotlinStdlibProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/ServiceLoaderProject.groovy
  src/functionalTest/groovy/com/autonomousapps/android/projects/VariantProject.groovy
  testkit/src/main/kotlin/com/autonomousapps/kit/Dependency.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/GradleProject.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/GradleProjectWriter.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/GradleProperties.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/RootProject.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/Source.kt
  testkit/src/main/kotlin/com/autonomousapps/kit/internal/Files.kt
Labels: internal, testing

#208 Solves #207
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
Labels: bug

#212 Added a functional test for onRedundantPlugins.
  src/functionalTest/groovy/com/autonomousapps/jvm/ConstantsSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/RedundantPluginsSpec.groovy
  src/functionalTest/groovy/com/autonomousapps/jvm/projects/RedundantPluginsProject.groovy
  src/main/kotlin/com/autonomousapps/advice/PluginAdvice.kt
Labels: internal, testing

#213 Fix redundant advice in transitive dependencies report.
  src/main/kotlin/com/autonomousapps/internal/advice/ComputedAdvice.kt
Labels: bug

#215 Partially resolves issue 205. Provides advice in the case of a particular build error.
  CHANGELOG.md
  build.gradle.kts
  src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt
  src/main/kotlin/com/autonomousapps/internal/UnitTestCompilationFailureListener.kt
  src/main/kotlin/com/autonomousapps/internal/analyzer/AndroidProjectAnalyzer.kt
Labels: enhancement
